### ISSUE TITLE
Regression: compilation fails when using `event.acceptTransferModes`

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#336]
Compilation error in ProScalaFX project
```
ProScalaFX/src/proscalafx/ch08/AudioPlayer3/AudioPlayer3.scala:44:48
type mismatch;
 found   : Array[scalafx.scene.input.TransferMode]
 required: Array[_ <: javafx.scene.input.TransferMode]
        event.acceptTransferModes(TransferMode.Any: _*)
```

Problem was introduced in commit c36b6cf074cbc1e34f2f1a070684f37d591c7e3e in `TransfterMode`:
```
val Any: Array[TransferMode] = jfxsi.TransferMode.ANY.map(TransferMode(_))
```
This changed type of `Any`. The type parameter of `Array` was changed from JavaFX type to ScalaFX type.
